### ISSUE TITLE
the template container does not run

### ISSUE THREAD

**Issue by thibauld** [algorun/algorun#16]
I tried to build and run the template container (algorun/algorun) but ran into an error : 

```
$ cd algorun/algorun
$ docker build .
Successfully built 5c0bbd2bac7c
$ docker run --name test 5c0bbd2bac7c
/node_modules/express/lib/application.js:209
    throw new TypeError('app.use() requires middleware functions');
          ^
TypeError: app.use() requires middleware functions
    at EventEmitter.use (/node_modules/express/lib/application.js:209:11)
    at Object.<anonymous> (/home/algorithm/Server.js:10:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

Even though there is no algorithm and this dummy container should not be able to do anything, it should be able to run with an error.

**Comment by thibauld** [comment]
Unfortunately, I still have the same issue:

```
$ docker run --name test2 91bcd2e87ac5

/node_modules/express/lib/application.js:209
    throw new TypeError('app.use() requires middleware functions');
          ^
TypeError: app.use() requires middleware functions
    at EventEmitter.use (/node_modules/express/lib/application.js:209:11)
    at Object.<anonymous> (/home/algorithm/Server.js:35:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by thibauld** [comment]
Also, if you want to debug the issue #16 (template container does not run), I was able to reproduce it on the digital ocean server (image f1a2832a729d).

```
# docker run --name test f1a2832a729d

/node_modules/express/lib/application.js:209
    throw new TypeError('app.use() requires middleware functions');
          ^
TypeError: app.use() requires middleware functions
    at EventEmitter.use (/node_modules/express/lib/application.js:209:11)
    at Object.<anonymous> (/home/algorithm/Server.js:35:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```
